### ISSUE TITLE
Dash separated names of icons cannot be imported in angular.

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/material-icons-extended#15]
When I try to import a single icon with name separated by dash an error "String literal expected" is thrown because angular does not support importing of dash separated modules.
For example:
import { add-row } from '@igniteui/material-icons-extended';
![icons1](https://user-images.githubusercontent.com/37667452/92926829-4ffb2000-f445-11ea-854a-fd8f2d71e37e.png)

**Comment by simeonoff** [comment]
There are no dash-separated exports. Icons are named and exported using camel case.

Try:
```ts
import { addRow } from '@igniteui/material-icons-extended';
```
