### ISSUE TITLE
Icons `all` and `is-true` are missing from `editor` category and `all` icon name is duplicated with all icons in the library.

### ISSUE THREAD

**Issue by skrustev** [IgniteUI/material-icons-extended#18]
## Description 
The `all` icon variable name is duplicated with the variable that contains all icons and both the `all` and `is-true` icons are missing from the `editor` category exported variable as well.

## Results
The `all` icon cannot be used currently and `is-true` needs to be imported additionally instead of using the `editor` category.

**Comment by StefanIvanov** [comment]
I noticed we were not exporting the all and is-true icons in the editor.ts file after defining them so with that I believe the issue will be fixed @simeonoff
