### ISSUE TITLE
DoesNotStartWith/EndWith Icons

### ISSUE THREAD

**Issue by ig-robstoffers** [IgniteUI/material-icons-extended#51]
`does-not-start-with` and `does-not-end-with` icons would be great if we could add them.
`previous-quarter` and `previous-week` icons would be great if we could add them.

**Comment by sdimchevski** [comment]
@ig-robstoffers can you give me context for these icons? what should they represent?

**Comment by ig-robstoffers** [comment]
Sorry, I should have included that initially.

They represent a string filter that checks whether an item does not start with (or end with) some text.

**Comment by StefanIvanov** [comment]
I added to the issue description to also include previous-quarter and previous-week icons
