### ISSUE TITLE
Create a new category and add all custom Ignite UI icons to it

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/material-icons-extended#8]
Create a new category and add all custom Ignite UI icons to it such as: pinning and filter conditions etc.

**Comment by simeonoff** [comment]
@StefanIvanov What should this category be called?

**Comment by StefanIvanov** [comment]
@simeonoff how about **ignite**

**Comment by StefanIvanov** [comment]
we will also need to add the new icons that are specified in #6

**Comment by simeonoff** [comment]
Hm, **ignite** sounds very generic and non-descriptive, especially compared to all other categories.
